//! Privacy-safe structured event schema.

use std::{fmt::Write, time::Duration};

use crate::metrics::{Operation, Outcome};

/// An internal request identifier generated by the server.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RequestId(pub u64);

/// Fields permitted in normal request-completion telemetry.
///
/// The type intentionally has nowhere to store input text, vectors, credentials,
/// model paths, or runtime error strings.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RequestEvent {
    /// Server-generated correlation identifier.
    pub request_id: RequestId,
    /// Stable operation class.
    pub operation: Operation,
    /// Stable outcome class.
    pub outcome: Outcome,
    /// Input count, bounded before telemetry is emitted.
    pub input_count: usize,
    /// Encoded request size.
    pub request_bytes: usize,
    /// Elapsed wall-clock duration.
    pub elapsed: Duration,
}

impl RequestEvent {
    /// Render newline-free logfmt suitable for a structured tracing field.
    #[must_use]
    pub fn to_logfmt(self) -> String {
        let mut output = String::new();
        let _ = write!(
            output,
            "event=request_complete request_id={} operation={:?} outcome={:?} input_count={} request_bytes={} elapsed_us={}",
            self.request_id.0,
            self.operation,
            self.outcome,
            self.input_count,
            self.request_bytes,
            self.elapsed.as_micros()
        );
        output
    }
}

/// Replace any diagnostic value with a stable privacy-safe classification.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DiagnosticClass {
    /// Configuration failed.
    Configuration,
    /// Runtime initialization failed.
    Runtime,
    /// Model operation failed.
    Model,
    /// Storage operation failed.
    Storage,
}

impl DiagnosticClass {
    /// Stable field suitable for ordinary telemetry.
    #[must_use]
    pub const fn code(self) -> &'static str {
        match self {
            Self::Configuration => "configuration_error",
            Self::Runtime => "runtime_error",
            Self::Model => "model_error",
            Self::Storage => "storage_error",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn telemetry_schema_cannot_contain_sensitive_sentinel() {
        let event = RequestEvent {
            request_id: RequestId(42),
            operation: Operation::Embed,
            outcome: Outcome::Failed,
            input_count: 1,
            request_bytes: 21,
            elapsed: Duration::from_millis(5),
        };
        let output = event.to_logfmt();
        assert!(!output.contains("sentinel-sensitive-input"));
        assert!(!output.contains(['\r', '\n']));
        assert!(output.contains("request_id=42"));
    }
}
